Repository Team-7-Coworkers/coworkers, pull requests merged in 2025-02, with the labels that each got.

#64 Feat/#63 팀 생성 수정 참여 페이지 퍼블
  app/[teamid]/modify/page.tsx
  app/addteam/layout.tsx
  app/addteam/page.tsx
  app/components/Button.tsx
  app/invitation/page.tsx
  app/styles/team.module.css
Labels: feature

#61 Feat/#25 리스트페이지 기능 구현
  app/[teamid]/tasklist/AddButton.tsx
  app/[teamid]/tasklist/Checkbox.tsx
  app/[teamid]/tasklist/CustomCalendar.css
  app/[teamid]/tasklist/CustomCalendar.tsx
  app/[teamid]/tasklist/ItemList.tsx
  app/[teamid]/tasklist/ListCategory.module.css
  app/[teamid]/tasklist/ListCategory.tsx
  app/[teamid]/tasklist/ListDate.tsx
  app/[teamid]/tasklist/ListHeader.tsx
  app/[teamid]/tasklist/RepeatDropdown.tsx
  app/[teamid]/tasklist/modals/AddListModal.tsx
  app/[teamid]/tasklist/modals/DeleteModal.tsx
  app/[teamid]/tasklist/modals/EditModal.tsx
  app/[teamid]/tasklist/modals/TodoModal.tsx
  app/[teamid]/tasklist/page.tsx
  app/api/task.api.ts
  app/components/Button.tsx
  app/components/TextField.tsx
  app/styles/globals.css
  app/styles/scrollbar.module.css
  app/teamid/tasklist/AddButton.tsx
  app/teamid/tasklist/ItemList.tsx
  app/teamid/tasklist/ListCategory.tsx
  app/teamid/tasklist/ListDate.tsx
  app/teamid/tasklist/ListHeader.tsx
  app/teamid/tasklist/mockdata.ts
  app/teamid/tasklist/page.tsx
  package-lock.json
  package.json
  public/images/icons/ic_down-arrow.svg
Labels: feature

#71 feat: 버튼 컴포넌트 링크 속성 추가
  app/components/Button.tsx
  app/dummy/button/page.tsx
  app/dummy/layout.tsx
  stories/Button.stories.tsx
Labels: feature

#66 feat/45 gnb 동작추가
  app/components/Dropdown/DropdownMenuItem.tsx
  app/components/Gnb/ProfileDropDown.tsx
  app/components/Gnb/TeamListDropDown.tsx
  app/components/Gnb/TeamListDropDownItem.tsx
  app/components/Gnb/TeamListSideBar.tsx
  app/components/Gnb/index.tsx
  app/layout.tsx
  app/libs/axios.ts
  app/stores/teamStore.ts
  app/stores/userStore.ts
  app/utils/navigation.ts
  public/images/icons/ic_dropdown-check.svg
  stories/Gnb/Gnb.stories.tsx
  tailwind.config.ts
Labels: feature

#68 Feat/#65 팀소속 없음 페이지
  app/noteam/page.tsx
  public/images/bg-no-team.png
Labels: feature

#72 Feat/#69 팀 생성 페이지 기능
  app/addteam/page.tsx
Labels: feature

#74 Feat/#73 팀 수정 페이지 기능
  app/[teamid]/modify/page.tsx
  app/[teamid]/page.tsx
  app/components/ImageUpload.tsx
  app/dummy/page.tsx
  app/not-found.tsx
  next.config.ts
Labels: feature

#75 Feat/67 간편로그인 및 기본동작 (카카오)
  app/api/auth.api.ts
  app/components/Gnb/index.tsx
  app/layout.tsx
  app/login/EasyLogin.tsx
  app/login/page.tsx
  app/oauth/kakao/page.tsx
  app/signup/SignupForm.tsx
  app/signup/page.tsx
  app/types/global.d.ts
  app/utils/KakaoScript.tsx
  app/utils/formValidators.ts
  public/images/icons/ic_google.svg
  public/images/icons/ic_kakaotalk.svg
Labels: feature

#77 Feat/60 자유게시판 상세페이지
  app/boards/LikeButton.tsx
  app/boards/PostActionDropdown.tsx
  app/boards/[articleId]/Comments.tsx
  app/boards/[articleId]/page.tsx
  app/types/article.d.ts
  app/types/shared/user.d.ts
  public/images/icons/ic-member.svg
Labels: feature

#82 Feat/#79 팀 참여 페이지 기능
  app/[teamid]/MemberList.tsx
  app/[teamid]/page.tsx
  app/invitation/page.tsx
  app/types/group.d.ts
Labels: feature

#81 Feat/#62 리스트상세페이지
  app/[teamid]/tasklist/CheckButton.tsx
  app/[teamid]/tasklist/CheckIcon.tsx
  app/[teamid]/tasklist/Checkbox.tsx
  app/[teamid]/tasklist/ItemList.tsx
  app/[teamid]/tasklist/KebobDropdown.tsx
  app/[teamid]/tasklist/ListCategory.tsx
  app/[teamid]/tasklist/info-displays/DateDisplay.tsx
  app/[teamid]/tasklist/info-displays/FrequencyDisplay.tsx
  app/[teamid]/tasklist/modals/EditModal.tsx
  app/[teamid]/tasklist/page.tsx
  app/[teamid]/tasklist/task-detail/SubmitIcon.tsx
  app/[teamid]/tasklist/task-detail/TaskComment.tsx
  app/[teamid]/tasklist/task-detail/TaskDetail.tsx
  app/[teamid]/tasklist/task-detail/TaskDetailHeader.tsx
  app/[teamid]/tasklist/task-detail/UserProfile.tsx
  app/api/taskComment.api.ts
  app/components/TextField.tsx
  app/stores/taskStore.ts
  app/types/shared/task.d.ts
  app/utils/date.ts
Labels: feature

#83 Feat/76 비밀번호 재설정 페이지 구현
  app/login/LoginForm.tsx
  app/login/ResetPasswordEmailModal.tsx
  app/login/page.tsx
  app/reset-password/ResetPasswordForm.tsx
  app/reset-password/page.tsx
  app/signup/page.tsx
  stories/LoginForm.stories.tsx
Labels: feature

#84 Feat/#59 마이히스토리 페이지
  app/myhistory/DailyItemList.tsx
  app/myhistory/page.tsx
  public/images/icons/ic_checked-box.svg
Labels: feature

#93 fix/#92--myhistory-빌드에러
  app/myhistory/page.tsx
Labels: bug, fix

#87 Fix/#86 모달 위치 문제 및 기타 해결
  app/components/Modal/Modal.module.css
  app/components/Modal/index.tsx
  app/dummy/layout.tsx
  app/dummy/modal/page.tsx
  tailwind.config.ts
Labels: bug, fix

#94 Feat/90 gnb 기능개선 및 추가
  app/components/Gnb/LoginMenu.tsx
  app/components/Gnb/ProfileDropDown.tsx
  app/components/Gnb/TeamListDropDown.tsx
  app/components/Gnb/TeamListDropDownItem.tsx
  app/components/Gnb/TeamListSideBar.tsx
  app/components/Gnb/index.tsx
  app/utils/navigation.ts
  package-lock.json
  package.json
  public/images/icons/ic_team.svg
Labels: feature

#97 Feat/#88 팀 페이지 기능 보수
  app/[teamid]/MemberListItem.tsx
  app/[teamid]/TaskLists.tsx
  app/[teamid]/TaskListsItem.tsx
  app/[teamid]/page.tsx
  app/[teamid]/teampage.module.css
  app/components/InputField.tsx
  app/components/Modal/index.tsx
  app/components/icons/PencilIcon.tsx
  app/constants/form.ts
  app/styles/globals.css
Labels: feature

#85 Feat/#78 랜딩 조건부 라우팅
  app/components/Landing/Section1.tsx
  app/components/Landing/Section2.tsx
  app/components/Landing/Section3.tsx
  app/components/Landing/ServiceIntro.tsx
  app/components/Landing/ServiceOutro.tsx
  app/constants/image.ts
Labels: feature

#104 Feat/90 gnb 기능개선 및 추가 (드롭다온 동기화 오류 및 ui개선)
  app/[teamid]/modify/page.tsx
  app/[teamid]/page.tsx
  app/addteam/page.tsx
  app/components/Gnb/ProfileDropDown.tsx
  app/components/Gnb/TeamListDropDown.tsx
  app/components/Gnb/TeamListDropDownItem.tsx
  app/components/Gnb/index.tsx
Labels: fix

#101 Feat/67 간편로그인 및 기본동작 (구글 로그인)
  app/api/auth/[...nextauth]/route.ts
  app/components/Gnb/ProfileDropDown.tsx
  app/libs/providers.tsx
  app/login/EasyLogin.tsx
  app/oauth/google/page.tsx
  app/stores/userStore.ts
  app/types/auth.d.ts
  app/types/global.d.ts
  app/types/kakao.d.ts
  app/types/next-auth.d.ts
  package-lock.json
  package.json
Labels: feature

#107 fix: 카카오 로그인 환경변수 누락 수정
  app/oauth/kakao/page.tsx
Labels: fix

#111 Refactor/#106 팀 페이지 리펙토링
  app/[teamid]/GroupInfo.tsx
  app/[teamid]/MemberList.tsx
  app/[teamid]/MemberListItem.tsx
  app/[teamid]/TaskListsItem.tsx
  app/[teamid]/layout.tsx
  app/[teamid]/page.tsx
  app/[teamid]/teampage.module.css
  app/addteam/page.tsx
  app/components/Img.tsx
  app/constants/form.ts
  app/dummy/layout.tsx
  app/dummy/page.tsx
  app/not-found.tsx
Labels: feature, fix, refactor

#112 Feat/#100 마이히스토리 추가기능
  app/myhistory/DailyItemList.tsx
  app/myhistory/FilterDropdown.tsx
  app/myhistory/page.tsx
  public/images/icons/ic_toggle.svg
Labels: feature

#113 Feat/108 계정설정페이지 구현
  app/components/ImageUpload.tsx
  app/mypage/ConfirnSecessionModal.tsx
  app/mypage/UpdatePasswordModal.tsx
  app/mypage/page.tsx
  app/stores/userStore.ts
  app/utils/formValidators.ts
  public/images/icons/ic_secession.svg
Labels: feature

#118 Refactor/#114 팀 페이지 작은 수정 및 리펙토링
  app/[teamid]/GroupInfo.tsx
  app/[teamid]/MemberList.tsx
  app/[teamid]/MemberListItem.tsx
  app/[teamid]/page.tsx
  app/[teamid]/teampage.module.css
  app/components/Img.tsx
  app/components/icons/CrownIcon.tsx
  app/components/icons/TrashIcon.tsx
  app/invitation/page.tsx
Labels: bug, feature

#119 Refactor/115 gnb 동기화 및 리팩토링
  app/components/Dropdown/DropdownMenuItem.tsx
  app/components/Gnb/ProfileDropDown.tsx
  app/components/Gnb/TeamListDropDown.tsx
  app/components/Gnb/TeamListDropDownItem.tsx
  app/components/Gnb/TeamListSideBar.tsx
  app/components/Gnb/index.tsx
  app/invitation/page.tsx
Labels: refactor

#126 feat/#123-토스트 추가 설정 및 테스트
  app/[teamid]/MemberList.tsx
  app/[teamid]/TaskLists.tsx
  app/[teamid]/modify/page.tsx
  app/[teamid]/page.tsx
  app/addteam/page.tsx
  app/layout.tsx
  app/styles/globals.css
  package-lock.json
  package.json
Labels: feature

#128 Feat/122 간편로그인 중간페이지
  app/hooks/useEasySignIn.ts
  app/oauth/EasyLoginLoadingPage.tsx
  app/oauth/google/page.tsx
  app/oauth/kakao/page.tsx
Labels: feature

#130 Feat/#124 마이히스토리 스켈레톤
  app/myhistory/LoadingMyhistory.tsx
  app/myhistory/layout.tsx
  app/myhistory/page.tsx
Labels: feature

#134 Refactor/132 로그인 회원가입 리팩토링
  app/api/auth.api.ts
  app/hooks/useEasySignIn.ts
  app/login/EasyLogin.tsx
  app/login/LoginForm.tsx
  app/login/ResetPasswordEmailModal.tsx
  app/login/page.tsx
  app/oauth/EasyLoginLoadingPage.tsx
  app/oauth/google/page.tsx
  app/oauth/kakao/page.tsx
  app/signup/SignupForm.tsx
  app/signup/page.tsx
  app/utils/createErrorHandler.ts
Labels: refactor

#133 Feat/#116 리스트페이지 추가기능
  app/[teamid]/tasklist/AddButton.tsx
  app/[teamid]/tasklist/Checkbox.tsx
  app/[teamid]/tasklist/CustomCalendar.tsx
  app/[teamid]/tasklist/ItemList.tsx
  app/[teamid]/tasklist/ListCategory.tsx
  app/[teamid]/tasklist/ListDate.tsx
  app/[teamid]/tasklist/ListHeader.tsx
  app/[teamid]/tasklist/layout.tsx
  app/[teamid]/tasklist/modals/EditModal.tsx
  app/[teamid]/tasklist/page.tsx
  app/[teamid]/tasklist/task-detail/CheckButton.tsx
  app/[teamid]/tasklist/task-detail/TaskComment.tsx
  app/[teamid]/tasklist/task-detail/TaskDetail.tsx
  app/[teamid]/tasklist/task-detail/TaskDetailHeader.tsx
  app/[teamid]/tasklist/task-icon/BackIcon.tsx
  app/[teamid]/tasklist/task-icon/CheckIcon.tsx
  app/[teamid]/tasklist/task-icon/SubmitIcon.tsx
  app/stores/taskStore.ts
  next.config.ts
  package-lock.json
Labels: feature, refactor

#139 Feat/136 자유게시판 qa반영
  app/boards/BestCardList.tsx
  app/boards/CardList.tsx
  app/boards/LikeButton.tsx
  app/boards/Pagination.tsx
  app/boards/PostActionDropdown.tsx
  app/boards/[articleId]/Comments.tsx
  app/boards/[articleId]/page.tsx
  app/boards/page.tsx
  app/boards/write/page.tsx
  app/constants/form.ts
Labels: enhancement, feature

#143 Refactor/138 gnb 기능개선 리팩토링
  app/components/Gnb/ProfileDropDown.tsx
  app/components/Gnb/TeamListDropDown.tsx
  app/components/Gnb/TeamListDropDownItem.tsx
  app/components/Gnb/TeamListSideBar.tsx
  app/components/Gnb/index.tsx
  app/layout.tsx
  tsconfig.json
Labels: refactor

#152 Refactor/#148 리스트페이지 qa반영
  app/[teamid]/tasklist/ItemList.tsx
  app/[teamid]/tasklist/KebobDropdown.tsx
  app/[teamid]/tasklist/ListCategory.tsx
  app/[teamid]/tasklist/ListDate.tsx
  app/[teamid]/tasklist/ListHeader.tsx
  app/[teamid]/tasklist/RepeatDropdown.tsx
  app/[teamid]/tasklist/modals/AddListModal.tsx
  app/[teamid]/tasklist/modals/TodoModal.tsx
  app/[teamid]/tasklist/page.tsx
  app/[teamid]/tasklist/task-detail/CheckButton.tsx
  app/[teamid]/tasklist/task-detail/TaskDetail.tsx
  app/[teamid]/tasklist/task-detail/UserProfile.tsx
Labels: feature, fix, refactor

#153 Refactor/151 계정설정페이지 리팩토링
  app/hooks/useEasySignIn.ts
  app/mypage/ConfirnSecessionModal.tsx
  app/mypage/MyPageForm.tsx
  app/mypage/UpdatePasswordModal.tsx
  app/mypage/page.tsx
  app/oauth/google/page.tsx
  app/oauth/kakao/page.tsx
  app/signup/SignupForm.tsx
  app/utils/formValidators.ts
Labels: feature, refactor

#155 Refactor/138 gnb 기능개선 리팩토링 (2차 작업)
  app/components/Gnb/ProfileDropDown.tsx
  app/components/Gnb/TeamListDropDown.tsx
  app/components/Gnb/TeamListDropDownItem.tsx
  app/components/Gnb/index.tsx
Labels: enhancement, refactor

#150 Feat/149 자유게시판 qa반영2차
  app/boards/BestCardList.tsx
  app/boards/CardList.tsx
  app/boards/PostActionDropdown.tsx
  app/boards/[articleId]/Comments.tsx
  app/boards/[articleId]/page.tsx
  app/boards/best/page.tsx
  app/boards/write/page.tsx
Labels: enhancement, feature

#156 feat/#154 범용 알림 모달
  app/components/Modal/AlertModal.tsx
  app/components/Modal/index.tsx
  app/dummy/modal/page.tsx
  app/hooks/.gitkeep
Labels: feature

#158 Feat/157 middleward 추가
  app/[teamid]/page.tsx
  app/boards/write/page.tsx
  app/components/Gnb/ProfileDropDown.tsx
  app/hooks/useEasySignIn.ts
  app/login/layout.tsx
  app/login/page.tsx
  app/mypage/page.tsx
  middleware.ts
Labels: feature

#160 Fix/159 카카오브라우저 안내 오류
  app/oauth/kakao/page.tsx
Labels: fix

#165 Feat/#161 랜딩메인이미지 수정
  app/components/Landing/ServiceIntro.tsx
  next.config.ts
  public/images/landing/landing-main-low.png
Labels: feature

#167 Refactor/162 비밀번호 재설정 리팩토링
  app/reset-password/page.tsx
  app/signup/SignupForm.tsx
Labels: fix, refactor

#169 Fix/159 카카오 state 검사 방식 수정
  app/login/EasyLogin.tsx
  app/oauth/kakao/page.tsx
Labels: fix

#166 Refactor/#163 리스트페이지 리펙토링
  app/[teamid]/tasklist/AddButton.tsx
  app/[teamid]/tasklist/ItemList.tsx
  app/[teamid]/tasklist/ListCategory.tsx
  app/[teamid]/tasklist/ListHeader.tsx
  app/[teamid]/tasklist/RepeatDropdown.tsx
  app/[teamid]/tasklist/layout.tsx
  app/[teamid]/tasklist/modals/AddListModal.tsx
  app/[teamid]/tasklist/modals/TodoModal.tsx
  app/[teamid]/tasklist/page.tsx
  app/[teamid]/tasklist/task-detail/CheckButton.tsx
  app/[teamid]/tasklist/task-detail/TaskComment.tsx
  app/[teamid]/tasklist/task-detail/TaskDetail.tsx
  app/[teamid]/tasklist/task-detail/TaskDetailHeader.tsx
  app/[teamid]/tasklist/task-detail/UserProfile.tsx
  app/myhistory/DailyItemList.tsx
Labels: refactor

#170 Fix/159 카카오브라우저 안내 오류 해결
  app/components/Gnb/ProfileDropDown.tsx
  app/oauth/kakao/page.tsx
  app/signup/page.tsx
Labels: fix

#181 Chore/171 axios 토큰갱신 alert제거
  app/libs/axios.ts
Labels: refactor

#172 Feat/131 자유게시판 리펙토링
  app/boards/BestCardList.tsx
  app/boards/Card.tsx
  app/boards/CardList.tsx
  app/boards/LikeButton.tsx
  app/boards/PostActionDropdown.tsx
  app/boards/[articleId]/Comments.tsx
  app/boards/[articleId]/page.tsx
  app/boards/best/page.tsx
  app/boards/page.tsx
  app/boards/write/page.tsx
  app/components/ImageUpload.tsx
Labels: enhancement, feature

#177 Fix/#173 마이히스토리 리스트 동기화
  app/[teamid]/tasklist/task-detail/CheckButton.tsx
  app/components/Landing/Section1.tsx
  app/components/Landing/Section2.tsx
  app/components/Landing/Section3.tsx
  app/components/Landing/ServiceIntro.tsx
  app/components/Landing/ServiceOutro.tsx
  app/myhistory/DailyItemList.tsx
  app/myhistory/FilterDropdown.tsx
  app/myhistory/page.tsx
  app/noteam/page.tsx
Labels: fix, refactor

#178 refactor/#176 noteam 개선
  app/noteam/page.tsx
Labels: feature, refactor

#175 Fix/#174 팀페이지 추가 qa 작업
  app/[teamid]/MemberList.tsx
  app/[teamid]/page.tsx
  app/invitation/page.tsx
  app/libs/utils.ts
Labels: feature, fix

#184 리스트페이지 탈퇴한 회원 할 일 상세 접근 시 에러 처리
  app/[teamid]/tasklist/modals/DeletedTaskModal.tsx
  app/[teamid]/tasklist/task-detail/TaskDetail.tsx
Labels: feature, fix

#185 Feat/183 스토리북 query provider 설정
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
Labels: feature

#189 🔨 refactor: 스토리북, 이미지 컴포넌트 수정
  app/components/ImageUpload.tsx
  stories/ImageUpload.stories.tsx
Labels: enhancement

#190 feat: 캘린더 스토리북 추가
  stories/CustomCalendar.stories.tsx
Labels: documentation

#191 docs/#187 스토리북 컴포넌트 추가
  stories/CircleGraph.stories.ts
Labels: documentation

#193 docs/ gnb 비로그인 스토리 파일 추가
  package-lock.json
  package.json
  stories/GNB.stories.tsx
Labels: documentation

#196 docs/#195 스토리북 기본 페이지 내용 추가
  stories/CircleGraph.stories.ts
  stories/Configure.mdx
  stories/Dropdown.stories.tsx
  stories/Input.stories.tsx
  stories/TextField.stories.ts
  stories/assets/accessibility.png
  stories/assets/accessibility.svg
  stories/assets/addon-library.png
  stories/assets/assets.png
  stories/assets/avif-test-image.avif
  stories/assets/context.png
  stories/assets/discord.svg
  stories/assets/docs.png
  stories/assets/figma-plugin.png
  stories/assets/github.svg
  stories/assets/share.png
  stories/assets/styling.png
  stories/assets/testing.png
  stories/assets/theming.png
  stories/assets/tutorials.svg
  stories/assets/youtube.svg
Labels: documentation

#198 리드미 업데이트
  README.md
Labels: documentation
